services:
  django-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    networks:
      - web-app-network

networks:
  web-app-network:
    external: true
