services:
  django-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./certs:/app/certs:ro  # Mount certificates as read-only
      - ./src/staticfiles:/app/src/staticfiles
    env_file:
      - .env
    networks:
      - web-app-network

networks:
  web-app-network:
    external: true
