
services:
  django-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - static_volume:/app/src/lolstreamers/staticfiles  # Add this line
      - ./certs:/app/certs:ro
    env_file:
      - .env
    networks:
      - web-app-network

volumes:
  static_volume:  # Add this volume definition

networks:
  web-app-network:
    external: true
