# Generated by Django 5.0.7 on 2024-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YtStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer_name', models.CharField(max_length=64)),
                ('youtube_id', models.CharField(max_length=64)),
                ('champion', models.CharField(max_length=20)),
                ('enemy_champion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'ytstreams',
            },
        ),
    ]
